---
# tasks - main.yml for nerve4-postgresql

- include_tasks: rhel-install-postgresql-base.yml
  when: 
    (ansible_distribution == "CentOS" and ansible_distribution_major_version == "8") or
    (ansible_distribution == "RedHat" and ansible_distribution_major_version == "8") or
    (ansible_distribution in "Rocky" and ansible_distribution_major_version == "8")

- include_tasks: ubuntu-install-postgresql-base.yml
  when: 
    - ansible_distribution == "Ubuntu"

- include_tasks: run-postgresql.yml